# Generated by Django 4.2.29 on 2026-03-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, help_text='Premium users only'),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, help_text='Premium users only'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, help_text='Premium users only'),
        ),
        migrations.AddField(
            model_name='mcqset',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, help_text='Premium users only'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, help_text='Premium users only'),
        ),
    ]
