# Generated by Django 4.2.29 on 2026-03-25 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_add_is_premium_to_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMCQProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ease_factor', models.FloatField(default=2.5, help_text='SM-2 ease factor (1.3 - 2.5)')),
                ('interval_days', models.IntegerField(default=1, help_text='Days until next review')),
                ('next_review_date', models.DateField(blank=True, help_text='When to review next', null=True)),
                ('last_rating', models.CharField(blank=True, choices=[('again', 'Again'), ('hard', 'Hard'), ('good', 'Good'), ('easy', 'Easy')], max_length=10, null=True)),
                ('times_seen', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('last_studied_at', models.DateTimeField(blank=True, null=True)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='models.mcq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MCQ Progress',
                'verbose_name_plural': 'MCQ Progress',
                'db_table': 'progress_mcq',
                'ordering': ['next_review_date', '-created_at'],
                'unique_together': {('user', 'mcq')},
            },
        ),
        migrations.CreateModel(
            name='UserFlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ease_factor', models.FloatField(default=2.5, help_text='SM-2 ease factor (1.3 - 2.5)')),
                ('interval_days', models.IntegerField(default=1, help_text='Days until next review')),
                ('next_review_date', models.DateField(blank=True, help_text='When to review next', null=True)),
                ('last_rating', models.CharField(blank=True, choices=[('again', 'Again'), ('hard', 'Hard'), ('good', 'Good'), ('easy', 'Easy')], max_length=10, null=True)),
                ('times_seen', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('last_studied_at', models.DateTimeField(blank=True, null=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='models.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flashcard Progress',
                'verbose_name_plural': 'Flashcard Progress',
                'db_table': 'progress_flashcard',
                'ordering': ['next_review_date', '-created_at'],
                'unique_together': {('user', 'flashcard')},
            },
        ),
    ]
