# Generated by Django 4.2.29 on 2026-03-26 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_usermcqprogress_userflashcardprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the field/course', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description shown to users before purchase')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price in USD. Set to 0 for free (but still requires purchase to access).', max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='If inactive, not visible to users')),
                ('creator', models.ForeignKey(help_text='The content creator who owns this field', limit_choices_to={'role': 'content_creator'}, on_delete=django.db.models.deletion.CASCADE, related_name='creator_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creator Field',
                'verbose_name_plural': 'Creator Fields',
                'db_table': 'content_creator_field',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='creator_field',
            field=models.ForeignKey(blank=True, help_text="If set, this set is part of a creator's paid field", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcard_sets', to='models.creatorfield'),
        ),
        migrations.AddField(
            model_name='mcqset',
            name='creator_field',
            field=models.ForeignKey(blank=True, help_text="If set, this set is part of a creator's paid field", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcq_sets', to='models.creatorfield'),
        ),
        migrations.CreateModel(
            name='CreatorFieldPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('creator_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='models.creatorfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creator Field Purchase',
                'verbose_name_plural': 'Creator Field Purchases',
                'db_table': 'content_creator_field_purchase',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'creator_field')},
            },
        ),
    ]
